branches:
  only:
  - master
language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq optipng
- sudo apt-get install -qq --no-install-recommends asciidoc
- git submodule update --init --recursive
install:
- if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ln -s /usr/share/asciidoc/asciidocapi.py
  ~/virtualenv/python2.7/lib/python2.7/site-packages/; fi
- pip install -r requirements/prod.txt
script: make publish
notifications:
  email:
    on_success: always
    on_failure: always
after_success: "./helper/deploy.sh"
env:
  global:
  - secure: mx/ChW4TioPlp8hiUbf0xyXuLpOBl/WbWLxpuWJxldr1eoly0iIcGjqHQ4fjFMiajTfCnkXFELhTr8AnWyAMT6zYK8qUmkNggFm+uR9LJI016adwVVJdheWDLbUNsWfKa9CH5kqFEE+qli1BX9BAFnS/l+1lPa6H9YcUQJABUF8=
