branches:
  only:
    - master

language: python

python:
    - '2.7'

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq optipng
    - sudo apt-get install -qq --no-install-recommends asciidoc
    - git submodule update --init --recursive

install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then ln -s /usr/share/asciidoc/asciidocapi.py ~/virtualenv/python2.7/lib/python2.7/site-packages/; fi
    - pip install -r requirements/prod.txt --use-mirrors

script: make publish

notifications:
  email:
    on_success: always
    on_failure: always

after_success: "./deploy.sh"

env:
  global:
    secure: bFLEmtouNIF9hME7GwETE+8whk1c2p1FF4DE+4jykNAJhhcSEZcNlowlf4+Uoz9rMZdqK8W6iIOsSTKh1bXBh1BZxerQB4BDly8966vDUr8xPWF2cBhzlnYodIhJv/EoAmHiWGMi/kxL7CKUG5hvQw4L/nXBOYzzCkZkwpsf2xc=
